### ISSUE TITLE
Clarification on inventory for vms 

### ISSUE THREAD

**Issue by dragonifnotifiswat** [ansible-collections/community.libvirt#109]
##### SUMMARY

Hello
Thanks for the work on this plugin, been trying to make it work the whole day. 
Bascilly I got kvm installed, hostname set, dns pointed to the host, guest-agent installed on vm but still cant make ansible connect. 

this is my basic inventory list 
      children:
        name
      hosts:
        ip of host
      vars:
         ansible_connection: community.libvirt.libvirt_qemu
         ansible_user: user
         ansible_password: password
         ansible_libvirt_uri: "qemu:///system"
         ansible_host: vm hostname

Maybe its better to just configure internal ssh and use that instead?
been trying  to read the docs and search for answers, any help would be apricicated. 

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

**Comment by csmart** [comment]
Hi @dragonifnotifiswat thanks for reaching out. The inventory should dynamically discovery your virtual machines, so all you should need to do is specify an inventory YAML file that has your connection information in it.

Can you create a simple `inventory.yml` file with your connection information in it, such as:

```yaml
ansible_connection: community.libvirt.libvirt_qemu
ansible_user: user
ansible_password: password
ansible_libvirt_uri: "qemu:///system"
```

Then try something like this to see if it discovers your machines?

`ansible-inventory inventory.yml --list`

**Comment by dragonifnotifiswat** [comment]
Thanks for the answer, to clarify a bit I was trying to connect to a remote vm via ssh

I ended up using this "qemu+ssh://username@ip/system?known_hosts=/path/to/known/host"

but it prompted me for the ssh password after every task, 
I ended up switching to just copying over the files via scp on the remote host.

**Comment by csmart** [comment]
Hi @dragonifnotifiswat it does support regular connection strings, so you should be able to use something like this to connect to a remote server, so long as you had an SSH key or some method to authenticate without a password.

```
plugin: community.libvirt.libvirt
uri: 'qemu+ssh://username@ip/system'
```
