### ISSUE TITLE
Is it really necessary to include both COPYING and LICENSE?

### ISSUE THREAD

**Issue by pghmcfc** [ansible-collections/community.libvirt#122]
##### SUMMARY
The collection includes both COPYING and LICENSE files, which are almost identical apart from whitespace and use of https:// URLs in LICENSE vs. http:// URLs in COPYING. Perhaps one could be removed? My suggestion would be to copy the contents of the (apparently more up to date) LICENSE file into the COPYING file and then get rid of the LICENSE file, since the COPYING file is referenced elsewhere in the collection.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
COPYING, LICENSE

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/paul/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/paul/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.0.1
  libyaml = True
```
(not that it matters)

**Comment by Andersson007** [comment]
@pghmcfc hello, SGTM, thank you for spotting it!
Would you like to submit a PR? If there are any questions, feel free to ask.
