### ISSUE TITLE
Rename repo to community.libvirt

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/community.libvirt#31]
##### SUMMARY
Hi,
To be more consistent with the other repos https://github.com/ansible-collections/ I'd like to rename this GitHub Repo to be `community.libvirt`

* Old URLs for issues and PRs will still work
* Old git URLs will work, though it will be good to update them locally
* We will need to update the URLs in `galaxy.yml`

Are you happy with this?
##### ISSUE TYPE
- Bug Report

**Comment by odyssey4me** [comment]
That's fine with me. I thought this might happen at some point, so better now than later.

**Comment by odyssey4me** [comment]
Closed-by: https://github.com/ansible-collections/community.libvirt/pull/32
