### ISSUE TITLE
virt module is not able to undefine a domain with defined nvram file

### ISSUE THREAD

**Issue by cueball23** [ansible-collections/community.libvirt#40]
##### SUMMARY

Virt module is not able to undefine a domain with defined nvram file.
migrated from: https://github.com/ansible/ansible/issues/43915
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

virt

##### ANSIBLE VERSION

```
ansible 2.6.2
python version = 2.7.12
```

##### STEPS TO REPRODUCE

```yaml
- name: undefine vm with nvram
  virt:
    name: example-vm-nvram
    command: undefine
```

##### EXPECTED RESULTS

domain "example-vm-nvram" is undefined
##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: libvirt.libvirtError: Requested operation is not valid: cannot delete inactive domain with nvram
fatal: [localhost]: FAILED! => {"changed": false, "failed_when_result": true, "msg": "Requested operation is not valid: cannot delete inactive domain with nvram"}
```
The libvirt function ```undefine``` is not able to remove a domain with nvram, by using ```undefineFlags``` it is possible to control the deletion of the nvram file. See:
https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainUndefine
https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainUndefineFlags

With the following command the undefine action is possible.
```
virsh undefine example-vm-nvram --nvram
```

**Comment by SichangHe** [comment]
This solution did not work for me, instead:
Go to the vm's configuration - Overview, XML tab, and find the line with `<nvram>`, it contains the nvram file.
Use `sudo` privilege to remove the nvram file.
Delete the vm without problem.
