### ISSUE TITLE
Fix wrong requirement in the modules doc

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.libvirt#86]
##### SUMMARY
All the modules / plugins should be checked on the wrong requirement `python-libvirt` that should be changed to `libvirt-python` as was spotted in https://github.com/ansible-collections/community.libvirt/pull/56#discussion_r672973821

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
Please check all the modules / plugins

**Comment by JensHeinrich** [comment]
On It

**Comment by JensHeinrich** [comment]
So I just understood the reason for the error:

`python-libvirt` is the name of an OS Package (which probably installs `libvirt-python` and other requirements).

Is there currenty some sort of best practices document for the requirements?
I really would like to make clear `libvirt-python` is a python/pip package and not an OS one.
Do you have suggestions?

**Comment by JensHeinrich** [comment]
In the `virt_net`-module there is a warning on the `libvirt`-module missing.
Maybe something like "`libvirt` python bindings" would be a better requirement?

**Comment by Andersson007** [comment]
@odyssey4me what do you think? ^

**Comment by odyssey4me** [comment]
Agreed, I think not mentioning a package name is the best way to work around differing package naming standards across different package sources. Personally, I'd be happy with 'libvirt python bindings' as the term to replace the package name.
